language: node_js

node_js:
- "0.10"
  
jdk:
- oraclejdk7
  
branches:
  only:
    - master
	
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - grunt